### PR TITLE
Add provisioning endpoint

### PR DESCRIPTION
**Pull request by caiolrosa**
- Add provisioning endpoint https://docs.justifi.tech/api-spec#tag/Provisioning/operation/ProductProvisioning
- Add deprecation  notice to `createSellerAccount`
- Improve bad request error response

### CODE REVIEW

**Review by pete2786 — APPROVED** [review]

**Comment by Claudia108** [comment]
How about the `createSubAccount()` function/endpoint? Should we deprecate that as well? Looks like it is a synonym to `createSellerAccount`.
https://github.com/justifi-tech/justifi-node/blob/ea61e7abe2e7259dedcc013667032b3d3e5c77d9/lib/internal/account.ts#L84

**Comment by caiolrosa** [comment]
```
ApiResponse {
  id: 'oe_3scP2zRZZ3xasrY9vOq37W',
  type: 'onboarding',
  data: {
    accountType: 'test',
    sellerAccountId: 'acc_4r157AicMS6nfYyjMWvze2',
    subAccountId: 'acc_4r157AicMS6nfYyjMWvze2',
    platformAccountId: 'acc_3FIbl3TIhTUBhXkwaTX59Z',
    payload: {
      onboardingVersion: 'v1.0',
      businessDetails: [Object],
      representative: [Object],
      bankAccount: [Object],
      termsAndConditions: [Object]
    }
  },
  pageInfo: null,
  idempotencyKey: undefined,
  request: JustifiRequest {
    maxRetries: 3,
    requestUrl: URL {
      href: 'https://api.justifi-staging.com/v1/entities/provisioning',
      origin: 'https://api.justifi-staging.com',
      protocol: 'https:',
      username: '',
      password: '',
      host: 'api.justifi-staging.com',
      hostname: 'api.justifi-staging.com',
      port: '',
      pathname: '/v1/entities/provisioning',
      search: '',
      searchParams: URLSearchParams {},
      hash: ''
    },
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      Accept: 'application/json',
      'User-Agent': 'justifi-node-0.2.5',
      Authorization: ' Bearer [REDACTED]'
    },
    body: {
      new_account_name: 'justifi node sdk provision 2',
      business_id: 'biz_FGGxR1u7Z2qUeFwtzIZmH',
      product_category: 'insurance'
    }
  }
}
```

**Comment by caiolrosa** [comment]
```
BadRequestError {
  code: 400,
  message: '{"error":{"code":"invalid_parameter","message":"The name provided for this account is already in use"}}'
}
```

**Review by Claudia108 — APPROVED** [review]
Looks good to me!

**Pull request merged**
